### ISSUE TITLE
BB 정리

### ISSUE THREAD

**Issue by jrog612** [1010235/iBooth#2]
번호 | 뜻
-----|-------
0 | 당신은 나의 0순위
90 | 가고있는중이다(GO)
100 | 돌아오라(BACK)
112 | 긴급상황
119 | 병원에 갔다
1004 | 당신의 천사로부터
1182 | 일을 빨리 진행하시오
1414 | 식사나 함께 합시다(식사식사)
10288 | 열이펄펄
1010235 | 열렬히 사모한다
1126611 | 여기 가운데에 선을 그으면 사랑해로 읽힌다.
1200 | 일이빵빵(지금바빠요)
1212 | 홀짝홀짝(술 마시자)
1254 | 이리오소
1255 | 내가있는곳으로오시오(일이오오)
12504 | 이리오십사
129129 | 난 지금 몸이아파
1365244 | 1년 365일 24시간 사랑해.
1472 | 우리 빨리 결혼해요,만사형통 일이 잘되고 있다(일사천리)
1486 | 사랑해
1577 | 대리운전
1717 | 일찍오세요
1750 | 일찍오렴
17175 | 일찍일찍와
17171771 | I LOVE YOU
1818 | ㅅㅍㅅㅍ
2080 | 치약!
230 | 이상...무
2222 | 이...(불만)
2255 | 이리로 와
2525 | 아주 좋았다
2626 | 이륙이륙(약속장소로 간다)
2848 | 이제그만만나요(이판사판)
3312042 | 심심하니 영화보러가자
486 | 사랑해 (글자를 쓸 때 - 사|4획, 랑|8획, 해|6획)
4242 | 자주연락해라(사이사이)
4444 | 死死死死
4860 | 우리사랑은 영원할것이다
494982535 | 사고났으니 빨리오세요
505 | S.O.S
404 | Not Found
5121 | 오늘기일, 오늘술한잔하자(오늘홀짝홀짝)
5151 | 기름이 떨어졌다(오일오일)
521000045 | 우리만나요
5825 | 오빠미워
5844 | 오빠를 사랑하는 사람
5882 | 오빠빨리 (전화해)
7142 | 친한사이
7179 | 친한친구
7205 | 오늘 미팅한다(있다)
7676 | 착륙 착륙(장소도착)
7700 | 드라이브하자(뛰뛰빵빵)
7788 | 기차타고 싶다(칙칙폭폭)
79337 | 친구야 힘내!
7942 | 친구사이
820(825) | 빨리와
8255 | 빨리와주세요
8282 | 빨리빨리
8578 | 바로 출발합시다
858555 | 바로바로 와요(술드시지 말고)
9090 | GO...GO
911 | 긴급출동
95258 | 굿모닝 오빠,안녕오빠
9797 | 구질구질
981 | 급한일
98258 | 굿바이..오빠
9977 | 할 이야기가 너무많다(구구절절)
9999 | 비둘기

**Comment by joyongjin** [comment]
일반 텍스트

0 : 당신은 나의 0순위
01 : 영원토록 변치말자
024 : 영원히 사랑해
0049 : 차에문제가생겼음(빵빵사고)
90 : 가고있는중이다(GO)
100 : 돌아오라(BACK)
0404 : 영원히 사랑해(영사영사)
0909 : 모든 것이 취소됐다(빵구빵구) 
0124 : 영원히 사랑해요
0242 : 연인사이
0285 : 몹시 아프다 
04 : 영원히 사랑해 
045 : 빵사와
0532 : 당신 모습이 상상어린다
112 : 긴급상황
119 : 병원에 갔다
1004 : 당신의 천사로부터
1182 : 일을 빨리 진행하시오
1414 : 식사나 함께 합시다(식사식사)
10288 : 열이펄펄
1010235 : 열렬히 사모한다
1126611 : 여기 가운데에 선을 그으면 사랑해로 읽힌다.
1200 : 일이빵빵(지금바빠요)
1212 : 홀짝홀짝(술 마시자)
1254 : 이리오소
1255 : 내가있는곳으로오시오(일이오오)
12504 : 이리오십사
129129 : 난 지금 몸이아파
1365244 : 1년 365일 24시간 사랑해.
1472 : 우리 빨리 결혼해요,만사형통 일이 잘되고 있다(일사천리)
1486 : 사랑해
15447979 - 대구사랑 대리운전
1577 : 대리운전
1717 : 일찍오세요
1750 : 일찍오렴
17175 : 일찍일찍와
17171771 : I LOVE YOU
1818 : ㅅㅍㅅㅍ
2080 : 치약!
230 : 이상...무
2222 : 이...(불만)
2255 : 이리로 와
2525 : 아주 좋았다
2626 : 이륙이륙(약속장소로 간다)
2848 : 이제그만만나요(이판사판)
3312042 : 심심하니 영화보러가자
486 : 사랑해 (글자를 쓸 때 - 사:4획, 랑:8획, 해:6획)
4242 : 자주연락해라(사이사이)
4444 : 死死死死
4860 : 우리사랑은 영원할것이다
494982535 : 사고났으니 빨리오세요
505 : S.O.S
404 : Not Found
5121 : 오늘기일, 오늘술한잔하자(오늘홀짝홀짝)
5151 : 기름이 떨어졌다(오일오일)
521000045 : 우리만나요
5825 : 오빠미워
5844 : 오빠를 사랑하는 사람
5882 : 오빠빨리 (전화해)
7142 : 친한사이
7179 : 친한친구
7205 : 오늘 미팅한다(있다)
7676 : 착륙 착륙(장소도착)
7700 : 드라이브하자(뛰뛰빵빵)
7788 : 기차타고 싶다(칙칙폭폭)
79337 : 친구야 힘내!
7942 : 친구사이
820(825) : 빨리와
8255 : 빨리와주세요
8282 : 빨리빨리
8578 : 바로 출발합시다
858555 : 바로바로 와요(술드시지 말고)
9090 : GO...GO
911 : 긴급출동
95258 : 굿모닝 오빠,안녕오빠
9797 : 구질구질
981 : 급한일
98258 : 굿바이..오빠
9977 : 할 이야기가 너무많다(구구절절)
9999 : 비둘기
